dtx:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: target/dev.duckdb
      threads: 2
    prod:
      type: duckdb
      path: target/prod.duckdb
      threads: 2
    staging:
      type: duckdb
      path: "md:stage?{{ env_var('motherduck_token') }}"
      